# Generated by Django 3.2 on 2021-04-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('college', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('skills', models.TextField()),
                ('other_details', models.TextField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('expectations', models.TextField()),
                ('availability', models.CharField(choices=[('Full-Time Internship', 'Full-Time Internship'), ('Part-Time Internship', 'Part-Time Internship'), ('Open-Source Contribution', 'Open-Source Contribution')], max_length=60)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('hired', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_ending', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.position')),
            ],
        ),
    ]
